// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLiteSample.Data;

#nullable disable

namespace SQLiteSample.Migrations
{
    [DbContext(typeof(RandomDataCenterContext))]
    partial class RandomDataCenterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("SQLiteSample.Models.RandomData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TheActualRandomData")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RandomDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
